server {
    listen 80;
    server_name peerprep16.duckdns.org;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name peerprep16.duckdns.org;

    ssl_certificate /etc/letsencrypt/live/peerprep16.duckdns.org/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/peerprep16.duckdns.org/privkey.pem;

    root /usr/share/nginx/html;
    index index.html;

    location /api/user/ {
        rewrite ^/api/user/(.*) /$1 break;
        set $upstream_user http://user-service:3001;
        proxy_pass $upstream_user;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/question/ {
        rewrite ^/api/question/(.*) /$1 break;
        set $upstream_question http://question-service:3002;
        proxy_pass $upstream_question;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/collaboration/ {
        rewrite ^/api/collaboration/(.*) /$1 break;
        set $upstream_collab http://collaboration-service:3003;
        proxy_pass $upstream_collab;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_cache_bypass $http_upgrade;
    }

    location /api/matching/ {
        rewrite ^/api/matching/(.*) /$1 break;
        set $upstream_matching http://matching-service:3004;
        proxy_pass $upstream_matching;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }


    location / {
        try_files $uri $uri/ /index.html;
    }
}
