# Redirect HTTP to HTTPS
server {
    listen 80;
    server_name peerprep16.duckdns.org;
    return 301 https://$host$request_uri;
}

# HTTPS
server {
    listen 443 ssl;
    server_name peerprep16.duckdns.org;

    ssl_certificate /etc/letsencrypt/live/peerprep16.duckdns.org/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/peerprep16.duckdns.org/privkey.pem;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }
}