const styles: { [key: string]: React.CSSProperties } = {
    heading: {
        fontSize: "20px",
        color: "#333",
        textAlign: "left",
        padding: 0,
        margin: "20px 0 20px 20px"
    },
    sidebar: {
        width: "200px",
        minHeight: "100vh",
        borderRight: "1px solid #000000",
        textAlign: "left" as const,
        left: 0,
        padding: 0,
    },
    tab: {
        display: "block",
        width: "100%",
        padding: "15px 20px",
        textAlign: "left",
        border: "none",
        backgroundColor: "transparent",
        cursor: "pointer",
        fontSize: "15px",
    },
    activeTab: {
        display: "block",
        width: "100%",
        padding: "15px 20px",
        textAlign: "left",
        border: "none",
        cursor: "pointer",
        fontSize: "15px",
        backgroundColor: "#ffffff",
        fontWeight: "bold",
    },
    searchBox: {
        display: "flex",
        alignItems: "center",
        gap: "8px",
        border: "1px solid #ccc",
        borderRadius: "20px",
        padding: "8px 16px",
        backgroundColor: "white",
        width: "300px",
    },
    searchInput: {
        border: "none",
        outline: "none",
        fontSize: "14px",
        width: "100%",
    },
    filterSelect: {
        padding: "8px 16px",
        borderRadius: "20px",
        border: "1px solid #ccc",
        fontSize: "14px",
        cursor: "pointer",
        backgroundColor: "white",
    },
    table: {
        width: "100%",
        borderCollapse: "collapse",
        backgroundColor: "white",
        borderRadius: "8px",
        overflow: "hidden",
        tableLayout: "fixed",

    },
    th: {
        textAlign: "left",
        padding: "12px 16px",
        borderBottom: "2px solid #ddd",
        fontSize: "14px",
        color: "#666",
        whiteSpace: "nowrap",
        cursor: "pointer",
    },
    tr: {
        borderBottom: "1px solid #eee",
    },
    td: {
        padding: "12px 16px",
        fontSize: "14px",
        textAlign: "left",
    },
    promoteButton: {
        padding: "6px 12px",
        backgroundColor: "#007BFF",
        color: "white",
        border: "none",
        borderRadius: "6px",
        cursor: "pointer",
        fontSize: "13px",
    },
    addQuestionButton: {
        padding: "10px 20px",
        backgroundColor: "white",
        border: "2px solid #333",
        borderRadius: "20px",
        fontWeight: "bold" as const,
        fontSize: "15px",
        cursor: "pointer",
    },

    modalOverlay: {
        position: "fixed" as const,
        top: 0,
        left: 0,
        width: "100%",
        height: "100%",
        backgroundColor: "rgba(0,0,0,0.5)",
        display: "flex",
        justifyContent: "center",
        alignItems: "center",
        zIndex: 1000,
    },
    modalBox: {
        backgroundColor: "white",
        padding: "40px",
        borderRadius: "12px",
        width: "500px",
        maxHeight: "80vh",
        overflowY: "auto" as const,
    },
    modalLabel: {
        display: "flex" as const,
        flexDirection: "column" as const,
        gap: "6px",
        marginBottom: "16px",
        fontSize: "14px",
        fontWeight: "bold" as const,
    },
    modalInput: {
        padding: "10px",
        borderRadius: "8px",
        border: "1px solid #ccc",
        fontSize: "14px",
        outline: "none",
        width: "100%",
        boxSizing: "border-box" as const,
    },

    container: {
        marginTop: "100px",
        textAlign: "center" as const,
        maxWidth: "280px",
        marginLeft: "auto",
        marginRight: "auto",
        display: "flex",
        flexDirection: "column" as const,
        alignItems: "center" as const,
    },
    navbarContainer: {
        border: "1px solid #ccc",
        padding: "5px",
        width: "100%",
        borderRadius: "8px",
        backgroundColor: "#ffffff",
        boxShadow: "0px 0px 10px rgba(0, 0, 0, 0.2)",
        position: "fixed" as const,
        top: 0,
        left: 0,
    },

    error: {
        color: "red",
    },
    input: {
        marginBottom: "5px",
        borderRadius: "10px",
        width: "250px",
        padding: "12px",
        border: "1px solid #ccc",
        outline: "none",
        boxSizing: "border-box" as const,
    },
    label: {
        marginBottom: "5px",
        textAlign: "left" as const,
        display: "block",
        width: "250px",
    },
    form: {
        maxWidth: "300px",
        margin: "0 auto",
    },

    button: {
        padding: "10px 20px",
        backgroundColor: "white",
        border: "2px solid #333",
        borderRadius: "20px",
        fontWeight: "bold" as const,
        fontSize: "15px",
        cursor: "pointer",
    },
    logoutButton: {
        padding: "10px 20px",
        backgroundColor: "white",
        border: "2px solid #333",
        borderRadius: "20px",
        fontWeight: "bold" as const,
        fontSize: "15px",
        cursor: "pointer",
    },
    link: {
        textDecoration: "none",
        color: "#007BFF",
    },

    passwordBorder: {
        backgroundColor: "#f5f5f5",
        border: "1px solid #ddd",
        borderRadius: "4px",
        padding: "12px",
        margin: "10px 0",
        fontSize: "14px",
        color: "#666",
        textAlign: "left" as const,
        width: "460px",
        marginBottom: "30px"
    },

    passwordRequirements: {
        margin: "5px 0",
        paddingLeft: "20px",
    },


    important: {
        fontSize: "16px",
        color: "red",
        marginTop: "0",
        textAlign: "left" as const,

    },

    normalText: {
        fontSize: "16px",
        color: "black",
        marginTop: "0",
        textAlign: "left" as const,

    },

    page: {
        marginTop: "80px",
        padding: "30px 40px",
    },

    sectionTitle: {
        fontSize: "18px",
        fontWeight: "bold" as const,
        marginBottom: "20px",
        marginLeft: "20px",
        marginRight: "20px",
        textAlign: "left" as const,
    },
    filtersRow: {
        display: "flex",
        gap: "40px",
        alignItems: "flex-start",
        marginBottom: "30px",
        justifyContent: "space-between",
    },
    filterGroup: {
        display: "flex",
        flexDirection: "column" as const,
        gap: "8px",
        flex: 1,
    },
    filterLabel: {
        fontSize: "16px",
        fontWeight: "bold" as const,
        textAlign: "left" as const,
        display: "block" as const,
    },
    select: {
        padding: "12px 16px",
        borderRadius: "10px",
        border: "1px solid #ccc",
        fontSize: "15px",
        width: "100%",
        backgroundColor: "white",
        cursor: "pointer",
    },
    matchmakeButton: {
        padding: "10px 20px",
        backgroundColor: "white",
        border: "2px solid #333",
        borderRadius: "20px",
        fontWeight: "bold" as const,
        fontSize: "15px",
        cursor: "pointer",
    },

    overlay: {
        position: "fixed",
        top: 0,
        left: 0,
        width: "100%",
        height: "100%",
        backgroundColor: "rgba(0,0,0,0.5)",
        display: "flex",
        justifyContent: "center",
        alignItems: "center",
        zIndex: 1000,
    },
    box: {
        backgroundColor: "white",
        padding: "40px",
        borderRadius: "12px",
        width: "400px",
        textAlign: "center",
        boxShadow: "0px 4px 20px rgba(0,0,0,0.2)",
    },
    spinner: {
        width: "50px",
        height: "50px",
        border: "5px solid #f0f0f0",
        borderTop: "5px solid #007BFF",
        borderRadius: "50%",
        animation: "spin 1s linear infinite",
        margin: "0 auto 20px auto",
    },
    cancelButton: {
        padding: "10px 30px",
        backgroundColor: "white",
        border: "2px solid red",
        borderRadius: "20px",
        color: "red",
        fontWeight: "bold",
        fontSize: "15px",
        cursor: "pointer",
    },
    acceptButton: {
        padding: "10px 30px",
        backgroundColor: "#007BFF",
        border: "none",
        borderRadius: "20px",
        color: "white",
        fontWeight: "bold",
        fontSize: "15px",
        cursor: "pointer",
    },
};

export default styles;